/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab.pkg6_josezuniga_31841432;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author josez
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        this.usuarios = new ArrayList<>();
        this.clanes = new ArrayList<>();
        initComponents();
        miUsuarioSecreto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        creacionUsuario = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        creaNom = new javax.swing.JTextField();
        creaApe = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        creaUser = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        creaPass = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        creaFecha = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        creaColor = new javax.swing.JButton();
        creaCrear = new javax.swing.JButton();
        jdPrincipal = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        tabCartas = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlClanAmiguitos = new javax.swing.JList<>();
        jLabel11 = new javax.swing.JLabel();
        jlClan = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        comboClan = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menupLogin = new javax.swing.JMenu();
        menupSalir = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        iniUser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        iniPass = new javax.swing.JPasswordField();
        iniIngresar = new javax.swing.JButton();
        iniCrear = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jLabel5.setText("Nombre");

        jLabel6.setText("Apellido");

        jLabel7.setText("Usuario");

        jLabel8.setText("Contraseña");

        jLabel9.setText("Fecha de Nacimiento");

        jLabel10.setText("Color Favorito");

        creaColor.setBackground(new java.awt.Color(255, 255, 0));
        creaColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creaColorActionPerformed(evt);
            }
        });

        creaCrear.setText("Crear Usuario");
        creaCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creaCrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(creaUser))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(creaNom, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(creaPass)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(creaApe, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(creaFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(creaColor))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(creaCrear)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(creaNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creaApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(creaUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(creaPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(creaFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(creaColor, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(creaCrear)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout creacionUsuarioLayout = new javax.swing.GroupLayout(creacionUsuario.getContentPane());
        creacionUsuario.getContentPane().setLayout(creacionUsuarioLayout);
        creacionUsuarioLayout.setHorizontalGroup(
            creacionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        creacionUsuarioLayout.setVerticalGroup(
            creacionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tabCartas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabCartasStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 731, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        tabCartas.addTab("Cartas", jPanel3);

        jlClanAmiguitos.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(jlClanAmiguitos);

        jLabel11.setText("Amigos del Clan");

        jlClan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlClan.setName("jlClan"); // NOI18N

        jLabel13.setText("Clanes disp.");

        jButton1.setText("Unirse al clan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jlClan)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(comboClan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(208, 208, 208))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(163, 163, 163))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlClan)
                .addGap(57, 57, 57)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(comboClan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        tabCartas.addTab("Amigos / Clan", jPanel4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabCartas)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabCartas)
                .addContainerGap())
        );

        menupLogin.setText("LoggIn");
        menupLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menupLoginActionPerformed(evt);
            }
        });
        jMenuBar1.add(menupLogin);

        menupSalir.setText("Salir");
        menupSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menupSalirActionPerformed(evt);
            }
        });
        jMenuBar1.add(menupSalir);

        jdPrincipal.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout jdPrincipalLayout = new javax.swing.GroupLayout(jdPrincipal.getContentPane());
        jdPrincipal.getContentPane().setLayout(jdPrincipalLayout);
        jdPrincipalLayout.setHorizontalGroup(
            jdPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jdPrincipalLayout.setVerticalGroup(
            jdPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Ingresar");

        jLabel2.setText("Usuario");

        jLabel3.setText("Contraseña");

        iniIngresar.setText("Ingresar");
        iniIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniIngresarActionPerformed(evt);
            }
        });

        iniCrear.setText("Crear Usuario");
        iniCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniCrearActionPerformed(evt);
            }
        });

        jLabel4.setText("No tiene usuario? Cree uno aqui:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(iniCrear)
                        .addGap(51, 51, 51))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(44, 44, 44))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(iniUser)
                            .addComponent(iniPass, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                        .addGap(141, 141, 141))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(iniIngresar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(iniUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(iniPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(iniIngresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iniCrear)
                    .addComponent(jLabel4))
                .addGap(80, 80, 80))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void creaColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creaColorActionPerformed
        Color c = JColorChooser.showDialog(this, "Eleccion Color", creaColor.getBackground());
        creaColor.setBackground(c);
        
    }//GEN-LAST:event_creaColorActionPerformed

    private void creaCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creaCrearActionPerformed
        String nombre, apellido, userName, password;
        Date fechaNacimiento;
        Color colorFav;
        nombre = creaNom.getText();
        apellido = creaApe.getText();
        userName= creaUser.getText();
        password = creaPass.getText();
        fechaNacimiento = creaFecha.getDate();
        colorFav = creaColor.getBackground();
        usuarios.add(new Usuario(nombre, apellido, userName, password, fechaNacimiento, colorFav));
        creaNom.setText("");
        creaApe.setText("");
        creaUser.setText("");
        creaPass.setText("");
        creaFecha.setDate(new Date());
        creacionUsuario.setVisible(false);
    }//GEN-LAST:event_creaCrearActionPerformed

    private void iniCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniCrearActionPerformed
        creacionUsuario.pack();
        creacionUsuario.setLocationRelativeTo(null);
        creacionUsuario.setVisible(true);
    }//GEN-LAST:event_iniCrearActionPerformed

    private void iniIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniIngresarActionPerformed
        boolean entro = false;
        for (Usuario usuario : usuarios) {
            if (usuario.getUserName().equals(iniUser.getText())) {
                if (usuario.getPassword().equals(iniPass.getText())) {
                    entro = true;
                    usuarioSelected = usuario;
                    iniPass.setText("");
                    iniUser.setText("");
                    jdPrincipal.pack();
                    jdPrincipal.setLocationRelativeTo(null);
                    jdPrincipal.setVisible(true);
                    setUsuario();
                    break;
                }
            }
        }
        if (!entro) {
            JOptionPane.showMessageDialog(this, "Error Usuario No encontrado!!!\nSi no tiene usuario lo puede crear");
            iniPass.setText("");
            iniUser.setText("");
        }
    }//GEN-LAST:event_iniIngresarActionPerformed

    private void menupLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menupLoginActionPerformed
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }//GEN-LAST:event_menupLoginActionPerformed

    private void tabCartasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabCartasStateChanged
        if (tabCartas.getSelectedIndex() == 1) {
            DefaultComboBoxModel comboModelo = (DefaultComboBoxModel)comboClan.getModel();
            for (Clan clan : clanes) {
                comboModelo.addElement(clan);
            }
            comboClan.setModel(comboModelo);
            if (tieneClan()) {
                jlClan.setText(usuarioSelectedClan.toString());
                DefaultListModel modeloLista = (DefaultListModel)jlClanAmiguitos.getModel();
                for (Usuario usuario : usuarioSelectedClan.getUsuarios()) {
                    if (usuario != usuarioSelected) {
                        modeloLista.addElement(usuario);
                    }
                }
            } else {
                jlClan.setText("No tiene Clan Actual");
                
            }
        }
    }//GEN-LAST:event_tabCartasStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (comboClan.getSelectedIndex() >= 0) {
            if (comboClan.getSelectedItem().toString().equals(jlClan.getText())) {
                JOptionPane.showMessageDialog(jdPrincipal, "Usted ya esta en ese clan");
            } else {
                for (Clan clan : clanes) {
                    if (clan.toString().equals(jlClan.getText())) {
                        for (Usuario usuario : clan.getUsuarios()) {
                            if (usuario.toString().equals(usuarioSelected.toString())) {
                                clan.getUsuarios().remove(usuario);
                            }
                        }
                    }
                    if (clan.toString().equals(comboClan.getSelectedItem().toString())) {
                        clan.setUsuario(usuarioSelected);
                    }
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void menupSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menupSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menupSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    private void setUsuario(){
        
    }
    
    private boolean tieneClan(){
        for (Clan clan : clanes) {
            System.out.println(clan.getUsuarios());
            for (Usuario usuario : clan.getUsuarios()) {
                System.out.println(usuario.toString());
                if (usuario.getUserName().equals(usuarioSelected.getUserName())) {
                    if (usuario.getPassword().equals(usuarioSelected.getPassword())) {
                        usuarioSelectedClan = clan;
                        return true;
                    }
                }
            }
        }
        return false;
    }
    
    private void miUsuarioSecreto(){
        Usuario usuarionuevo = new Usuario("Jose", "Zuniga", "zunigajose21", "lab6", new Date(2000, 9, 8), Color.BLUE);
        usuarios.add(usuarionuevo);
        clanes.add(new Clan("loskillers", "Oro", new Date(), usuarioSelected));
        ((Clan)clanes.get(0)).setUsuario(usuarionuevo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboClan;
    private javax.swing.JTextField creaApe;
    private javax.swing.JButton creaColor;
    private javax.swing.JButton creaCrear;
    private com.toedter.calendar.JDateChooser creaFecha;
    private javax.swing.JTextField creaNom;
    private javax.swing.JPasswordField creaPass;
    private javax.swing.JTextField creaUser;
    private javax.swing.JDialog creacionUsuario;
    private javax.swing.JButton iniCrear;
    private javax.swing.JButton iniIngresar;
    private javax.swing.JPasswordField iniPass;
    private javax.swing.JTextField iniUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JDialog jdPrincipal;
    private javax.swing.JLabel jlClan;
    private javax.swing.JList<String> jlClanAmiguitos;
    private javax.swing.JMenu menupLogin;
    private javax.swing.JMenu menupSalir;
    private javax.swing.JTabbedPane tabCartas;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Usuario> usuarios = new ArrayList<>();
    private Usuario usuarioSelected;
    private ArrayList<Clan> clanes;
    private Clan usuarioSelectedClan;
}
