/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab.pkg6_josezuniga_31841432;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author josez
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        this.usuarios = new ArrayList<>();
        this.clanes = new ArrayList<>();
        initComponents();
        miUsuarioSecreto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        creacionUsuario = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        creaNom = new javax.swing.JTextField();
        creaApe = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        creaUser = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        creaPass = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        creaFecha = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        creaColor = new javax.swing.JButton();
        creaCrear = new javax.swing.JButton();
        jdPrincipal = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        tabCartas = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        arbolitoLindo = new javax.swing.JTree();
        cartaAgregar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlClanAmiguitos = new javax.swing.JList<>();
        jLabel11 = new javax.swing.JLabel();
        jlClan = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        comboClan = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menupLogin = new javax.swing.JMenu();
        menupSalir = new javax.swing.JMenu();
        crearClan = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        clanNom = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        clantipo = new javax.swing.JComboBox<>();
        opClan = new javax.swing.JButton();
        CrearCarta = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        crearcartaCombo = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        cartasNombre = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cartasVida = new javax.swing.JTextField();
        cartasDanio = new javax.swing.JTextField();
        menuPopUp = new javax.swing.JPopupMenu();
        VerInfo = new javax.swing.JMenuItem();
        Modificar = new javax.swing.JMenuItem();
        InfoCartas = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        verVida = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        verNombre = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        verTipo = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        verDanio = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        verElixir = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        iniUser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        iniPass = new javax.swing.JPasswordField();
        iniIngresar = new javax.swing.JButton();
        iniCrear = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jLabel5.setText("Nombre");

        jLabel6.setText("Apellido");

        jLabel7.setText("Usuario");

        jLabel8.setText("Contraseña");

        jLabel9.setText("Fecha de Nacimiento");

        jLabel10.setText("Color Favorito");

        creaColor.setBackground(new java.awt.Color(255, 255, 0));
        creaColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creaColorActionPerformed(evt);
            }
        });

        creaCrear.setText("Crear Usuario");
        creaCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creaCrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(creaUser))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(creaNom, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(creaPass)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(creaApe, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(creaFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(creaColor))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(creaCrear)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(creaNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creaApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(creaUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(creaPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(creaFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(creaColor, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(creaCrear)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout creacionUsuarioLayout = new javax.swing.GroupLayout(creacionUsuario.getContentPane());
        creacionUsuario.getContentPane().setLayout(creacionUsuarioLayout);
        creacionUsuarioLayout.setHorizontalGroup(
            creacionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        creacionUsuarioLayout.setVerticalGroup(
            creacionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tabCartas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabCartasStateChanged(evt);
            }
        });
        tabCartas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tabCartasFocusGained(evt);
            }
        });

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Mazo");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Mazo 1");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Mazo 2");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Mazo 3");
        treeNode1.add(treeNode2);
        arbolitoLindo.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        arbolitoLindo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arbolitoLindoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(arbolitoLindo);

        cartaAgregar.setText("Agregar Carta");
        cartaAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartaAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(cartaAgregar)
                .addGap(65, 65, 65)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(cartaAgregar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        tabCartas.addTab("Cartas", jPanel3);

        jlClanAmiguitos.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(jlClanAmiguitos);

        jLabel11.setText("Amigos del Clan");

        jlClan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlClan.setName("jlClan"); // NOI18N

        jLabel13.setText("Clanes disp.");

        jButton1.setText("Unirse al clan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Crear Clan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jlClan)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(comboClan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(89, 89, 89))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(44, 44, 44))
                                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(186, 186, 186))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlClan)
                .addGap(57, 57, 57)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(comboClan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(93, 93, 93)
                        .addComponent(jButton2)))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        tabCartas.addTab("Amigos / Clan", jPanel4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabCartas, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabCartas)
                .addContainerGap())
        );

        menupLogin.setText("LoggIn");
        menupLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menupLoginActionPerformed(evt);
            }
        });
        jMenuBar1.add(menupLogin);

        menupSalir.setText("Salir");
        menupSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menupSalirActionPerformed(evt);
            }
        });
        jMenuBar1.add(menupSalir);

        jdPrincipal.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout jdPrincipalLayout = new javax.swing.GroupLayout(jdPrincipal.getContentPane());
        jdPrincipal.getContentPane().setLayout(jdPrincipalLayout);
        jdPrincipalLayout.setHorizontalGroup(
            jdPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jdPrincipalLayout.setVerticalGroup(
            jdPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel12.setText("Nombre");

        jLabel14.setText("Tipo");

        clantipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bronce", "Plata", "Oro", "Legendario" }));

        opClan.setText("Crear Clan");
        opClan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opClanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(clanNom)
                            .addComponent(clantipo, 0, 159, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(opClan)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(clanNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(clantipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86)
                .addComponent(opClan)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout crearClanLayout = new javax.swing.GroupLayout(crearClan.getContentPane());
        crearClan.getContentPane().setLayout(crearClanLayout);
        crearClanLayout.setHorizontalGroup(
            crearClanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crearClanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        crearClanLayout.setVerticalGroup(
            crearClanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crearClanLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Mazo:");

        crearcartaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mazo 1", "Mazo 2", "Mazo 3" }));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Tipo Carta");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Minipekka", "Montapuerco", "Golem", "Leñador", "Dragon Infernal", "Dragon", "Gigante Noble", "Pandilla de Duendes" }));

        jButton3.setText("Agregar a Mazo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Nombre");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Vida");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Daño");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jButton3))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(36, 36, 36)
                                .addComponent(crearcartaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cartasNombre)
                                    .addComponent(cartasVida)
                                    .addComponent(cartasDanio))))))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(crearcartaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cartasNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(cartasVida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(cartasDanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout CrearCartaLayout = new javax.swing.GroupLayout(CrearCarta.getContentPane());
        CrearCarta.getContentPane().setLayout(CrearCartaLayout);
        CrearCartaLayout.setHorizontalGroup(
            CrearCartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        CrearCartaLayout.setVerticalGroup(
            CrearCartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        VerInfo.setText("Ver Info");
        VerInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerInfoActionPerformed(evt);
            }
        });
        menuPopUp.add(VerInfo);

        Modificar.setText("Modificar");
        menuPopUp.add(Modificar);

        jLabel20.setText("Nombre");

        verVida.setEditable(false);

        jLabel21.setText("Vida");

        verNombre.setEditable(false);

        jLabel22.setText("Daño");

        verTipo.setEditable(false);

        jLabel23.setText("Tipo");

        verDanio.setEditable(false);

        jLabel24.setText("Elixir");

        verElixir.setEditable(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel20)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addGap(70, 70, 70)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(verTipo)
                    .addComponent(verNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(verVida)
                    .addComponent(verDanio)
                    .addComponent(verElixir))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(verNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(verVida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel21)))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(verDanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(verTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(verElixir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout InfoCartasLayout = new javax.swing.GroupLayout(InfoCartas.getContentPane());
        InfoCartas.getContentPane().setLayout(InfoCartasLayout);
        InfoCartasLayout.setHorizontalGroup(
            InfoCartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        InfoCartasLayout.setVerticalGroup(
            InfoCartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Ingresar");

        jLabel2.setText("Usuario");

        jLabel3.setText("Contraseña");

        iniIngresar.setText("Ingresar");
        iniIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniIngresarActionPerformed(evt);
            }
        });

        iniCrear.setText("Crear Usuario");
        iniCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniCrearActionPerformed(evt);
            }
        });

        jLabel4.setText("No tiene usuario? Cree uno aqui:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(iniCrear)
                        .addGap(51, 51, 51))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(44, 44, 44))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(iniUser)
                            .addComponent(iniPass, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                        .addGap(141, 141, 141))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(iniIngresar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(iniUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(iniPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(iniIngresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iniCrear)
                    .addComponent(jLabel4))
                .addGap(80, 80, 80))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void creaColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creaColorActionPerformed
        Color c = JColorChooser.showDialog(this, "Eleccion Color", creaColor.getBackground());
        creaColor.setBackground(c);
        
    }//GEN-LAST:event_creaColorActionPerformed

    private void creaCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creaCrearActionPerformed
        String nombre, apellido, userName, password;
        Date fechaNacimiento;
        Color colorFav;
        nombre = creaNom.getText();
        apellido = creaApe.getText();
        userName= creaUser.getText();
        password = creaPass.getText();
        fechaNacimiento = creaFecha.getDate();
        colorFav = creaColor.getBackground();
        usuarios.add(new Usuario(nombre, apellido, userName, password, fechaNacimiento, colorFav));
        creaNom.setText("");
        creaApe.setText("");
        creaUser.setText("");
        creaPass.setText("");
        creaFecha.setDate(new Date());
        creacionUsuario.setVisible(false);
    }//GEN-LAST:event_creaCrearActionPerformed

    private void iniCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniCrearActionPerformed
        creacionUsuario.pack();
        creacionUsuario.setLocationRelativeTo(null);
        creacionUsuario.setVisible(true);
    }//GEN-LAST:event_iniCrearActionPerformed

    private void iniIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniIngresarActionPerformed
        boolean entro = false;
        for (Usuario usuario : usuarios) {
            if (usuario.getUserName().equals(iniUser.getText())) {
                if (usuario.getPassword().equals(iniPass.getText())) {
                    entro = true;
                    usuarioSelected = usuario;
                    iniPass.setText("");
                    iniUser.setText("");
                    jdPrincipal.pack();
                    jdPrincipal.setLocationRelativeTo(null);
                    jdPrincipal.setVisible(true);
                    setUsuario();
                    break;
                }
            }
        }
        if (!entro) {
            JOptionPane.showMessageDialog(this, "Error Usuario No encontrado!!!\nSi no tiene usuario lo puede crear");
            iniPass.setText("");
            iniUser.setText("");
        }
    }//GEN-LAST:event_iniIngresarActionPerformed

    private void menupLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menupLoginActionPerformed
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }//GEN-LAST:event_menupLoginActionPerformed

    private void tabCartasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabCartasStateChanged
        if (tabCartas.getSelectedIndex() == 1) {
            DefaultComboBoxModel comboModelo = new DefaultComboBoxModel();
            for (Clan clan : clanes) {
                comboModelo.addElement(clan);
            }
            comboClan.setModel(comboModelo);
            if (tieneClan()) {
                jlClan.setText(usuarioSelectedClan.toString());
                DefaultListModel modeloLista = (DefaultListModel)jlClanAmiguitos.getModel();
                for (Usuario usuario : usuarioSelectedClan.getUsuarios()) {
                    if (usuario != usuarioSelected) {
                        modeloLista.addElement(usuario);
                    }
                }
            } else {
                jlClan.setText("No tiene Clan Actual");
                
            }
        }
    }//GEN-LAST:event_tabCartasStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultListModel modelo = new DefaultListModel();
        Usuario x = new Usuario();
        int y = 0;
        if (comboClan.getSelectedIndex() >= 0) {
            if (comboClan.getSelectedItem().toString().equals(jlClan.getText())) {
                JOptionPane.showMessageDialog(jdPrincipal, "Usted ya esta en ese clan");
            } else {
                for (Clan clan : clanes) {
                    if (clan.toString().equals(jlClan.getText())) {
                        for (Usuario usuario : clan.getUsuarios()) {
                            if (usuario.toString().equals(usuarioSelected.toString())) {
                                x = usuario;
                                y = clanes.indexOf(clan);
                            }
                        }
                    }
                    ((Clan)clanes.get(y)).getUsuarios().remove(x);
                    if (clan.toString().equals(comboClan.getSelectedItem().toString())) {
                        for (Usuario usuario : clan.getUsuarios()) {
                            modelo.addElement(usuario);
                        }
                        clan.setUsuario(usuarioSelected);
                    }
                }
                jlClanAmiguitos.setModel(modelo);
            }
        }
        tabCartas.setSelectedIndex(0);
        tabCartas.setSelectedIndex(1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void menupSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menupSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menupSalirActionPerformed

    private void opClanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opClanActionPerformed
        boolean error = false;
        try {
            clanes.add(new Clan(clanNom.getText(), clantipo.getSelectedItem().toString(), new Date(), usuarioSelected));
        } catch (Exception e) {
            error = true;
            JOptionPane.showMessageDialog(crearClan, "Ocurrio un Error super fatal");
        }
        if (!error) {
            tabCartas.setSelectedIndex(0);
            tabCartas.setSelectedIndex(1);
            crearClan.setVisible(false);
            clanNom.setText("");
        }
    }//GEN-LAST:event_opClanActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        crearClan.setLocationRelativeTo(null);
        crearClan.pack();
        crearClan.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tabCartasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tabCartasFocusGained
        if (tabCartas.getSelectedIndex() == 1) {
            DefaultComboBoxModel comboModelo = new DefaultComboBoxModel();
            for (Clan clan : clanes) {
                comboModelo.addElement(clan);
            }
            comboClan.setModel(comboModelo);
        }
    }//GEN-LAST:event_tabCartasFocusGained

    private void arbolitoLindoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arbolitoLindoMouseClicked
        if (evt.isMetaDown()) {
            int row = arbolitoLindo.getClosestRowForLocation(evt.getX(), evt.getY());
            arbolitoLindo.setSelectionRow(row);
            Object v1 = arbolitoLindo.getSelectionPath().getLastPathComponent();
            nodoSeleccionado = (DefaultMutableTreeNode) v1;
            if (nodoSeleccionado.getUserObject() instanceof Cartas) {
                menuPopUp.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_arbolitoLindoMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        boolean error = false;
        try {
            Integer.parseInt(cartasDanio.getText());
            Integer.parseInt(cartasVida.getText());
        } catch (Exception e) {
            error = true;
            JOptionPane.showMessageDialog(CrearCarta, "Ocurrio un error bien feo!");
        }
        if (!error) {
            DefaultTreeModel modeloA = (DefaultTreeModel) arbolitoLindo.getModel();
            DefaultMutableTreeNode nodoNuevo;
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloA.getRoot();
            Cartas carta = new Cartas() {
                @Override
                public String velocidad() {
                    return "";
                }

                @Override
                public int costeElixir() {
                    return 0;
                }

                @Override
                public String tipo() {
                    return "";
                }

                @Override
                public String objetivo() {
                    return "";
                }
            };
            switch (crearcartaCombo.getSelectedIndex()) {
                case 0:
                    carta = new Minipekka(cartasNombre.getText(), Integer.parseInt(cartasVida.getText()), Integer.parseInt(cartasDanio.getText()));
                    break;
                case 1:
                    carta = new Montapuerco(cartasNombre.getText(), Integer.parseInt(cartasVida.getText()), Integer.parseInt(cartasDanio.getText()));
                    break;
                case 2:
                    carta = new Golem(cartasNombre.getText(), Integer.parseInt(cartasVida.getText()), Integer.parseInt(cartasDanio.getText()));
                    break;
                case 3:
                    carta = new Leñador(cartasNombre.getText(), Integer.parseInt(cartasVida.getText()), Integer.parseInt(cartasDanio.getText()));
                    break;
                case 4:
                    carta = new Dragon_Infernal(cartasNombre.getText(), Integer.parseInt(cartasVida.getText()), Integer.parseInt(cartasDanio.getText()));
                    break;
                case 5:
                    carta = new Dragon(cartasNombre.getText(), Integer.parseInt(cartasVida.getText()), Integer.parseInt(cartasDanio.getText()));
                    break;
                case 6:
                    carta = new GiganteNoble(cartasNombre.getText(), Integer.parseInt(cartasVida.getText()), Integer.parseInt(cartasDanio.getText()));
                    break;
                case 7:
                    carta = new PandillaDuendes(cartasNombre.getText(), Integer.parseInt(cartasVida.getText()), Integer.parseInt(cartasDanio.getText()));
                    System.out.println(carta.tipo());
                    break;
            }
            ArrayList< Cartas> m1 = new ArrayList<>();
            boolean existe = false;
            DefaultMutableTreeNode nodox;
            for (int i = 0; i < raiz.getChildCount(); i++) {
                if (raiz.getChildAt(i).toString().equals(crearcartaCombo.getSelectedItem().toString())) {
                    if (!hay3((DefaultMutableTreeNode) raiz.getChildAt(i))) {
                        for (int j = 0; j < raiz.getChildAt(i).getChildCount(); j++) {
                            if (raiz.getChildAt(i).getChildAt(j).toString().equals(carta.tipo())) {
                                ((DefaultMutableTreeNode) raiz.getChildAt(i).getChildAt(j)).add(new DefaultMutableTreeNode(carta));
                                existe = true;
                                break;
                            }
                        }
                        if (!existe) {
                            nodox = (new DefaultMutableTreeNode(carta.tipo()));
                            ((DefaultMutableTreeNode) nodox).add(new DefaultMutableTreeNode(carta));
                            for (int j = 0; j < raiz.getChildCount(); j++) {
                                if (raiz.getChildAt(i).toString().equals(crearcartaCombo.getSelectedItem().toString())) {
                                    ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(nodox);
                                }
                            }
                        }
                    } else {
                        JOptionPane.showMessageDialog(CrearCarta, "Ya existen tres elementos!!!");
                    }
                }
            }
            modeloA.reload();
            cartasDanio.setText("");
            cartasNombre.setText("");
            cartasVida.setText("");
            CrearCarta.setVisible(false);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cartaAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartaAgregarActionPerformed
        CrearCarta.pack();
        CrearCarta.setLocationRelativeTo(jdPrincipal);
        CrearCarta.setVisible(true);
    }//GEN-LAST:event_cartaAgregarActionPerformed

    private void VerInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerInfoActionPerformed
        verNombre.setText(((Cartas)nodoSeleccionado.getUserObject()).getNombre());
        verDanio.setText(String.valueOf(((Cartas)nodoSeleccionado.getUserObject()).getPuntosDanio()));
        verVida.setText(String.valueOf(((Cartas)nodoSeleccionado.getUserObject()).getPuntosVida()));
        verTipo.setText(((Cartas)nodoSeleccionado.getUserObject()).tipo());
        verElixir.setText(String.valueOf(((Cartas)nodoSeleccionado.getUserObject()).costeElixir()));
        InfoCartas.pack();
        InfoCartas.setLocationRelativeTo(jdPrincipal);
        InfoCartas.setVisible(true);
    }//GEN-LAST:event_VerInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    private void setUsuario(){
        
    }
    
    private boolean hay3(DefaultMutableTreeNode nodo){
        if (nodo.getChildCount() >= 3) {
            return true;
        }
        return false;
    }
    
    private boolean tieneClan(){
        for (Clan clan : clanes) {
            System.out.println(clan.getUsuarios());
            for (Usuario usuario : clan.getUsuarios()) {
                System.out.println(usuario.toString());
                if (usuario.getUserName().equals(usuarioSelected.getUserName())) {
                    if (usuario.getPassword().equals(usuarioSelected.getPassword())) {
                        usuarioSelectedClan = clan;
                        return true;
                    }
                }
            }
        }
        return false;
    }
    
    private void miUsuarioSecreto(){
        Usuario usuarionuevo = new Usuario("Jose", "Zuniga", "zunigajose21", "lab6", new Date(2000, 9, 8), Color.BLUE);
        usuarios.add(usuarionuevo);
        clanes.add(new Clan("loskillers", "Oro", new Date(), usuarioSelected));
        ((Clan)clanes.get(0)).setUsuario(usuarionuevo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog CrearCarta;
    private javax.swing.JDialog InfoCartas;
    private javax.swing.JMenuItem Modificar;
    private javax.swing.JMenuItem VerInfo;
    private javax.swing.JTree arbolitoLindo;
    private javax.swing.JButton cartaAgregar;
    private javax.swing.JTextField cartasDanio;
    private javax.swing.JTextField cartasNombre;
    private javax.swing.JTextField cartasVida;
    private javax.swing.JTextField clanNom;
    private javax.swing.JComboBox<String> clantipo;
    private javax.swing.JComboBox<String> comboClan;
    private javax.swing.JTextField creaApe;
    private javax.swing.JButton creaColor;
    private javax.swing.JButton creaCrear;
    private com.toedter.calendar.JDateChooser creaFecha;
    private javax.swing.JTextField creaNom;
    private javax.swing.JPasswordField creaPass;
    private javax.swing.JTextField creaUser;
    private javax.swing.JDialog creacionUsuario;
    private javax.swing.JDialog crearClan;
    private javax.swing.JComboBox<String> crearcartaCombo;
    private javax.swing.JButton iniCrear;
    private javax.swing.JButton iniIngresar;
    private javax.swing.JPasswordField iniPass;
    private javax.swing.JTextField iniUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JDialog jdPrincipal;
    private javax.swing.JLabel jlClan;
    private javax.swing.JList<String> jlClanAmiguitos;
    private javax.swing.JPopupMenu menuPopUp;
    private javax.swing.JMenu menupLogin;
    private javax.swing.JMenu menupSalir;
    private javax.swing.JButton opClan;
    private javax.swing.JTabbedPane tabCartas;
    private javax.swing.JTextField verDanio;
    private javax.swing.JTextField verElixir;
    private javax.swing.JTextField verNombre;
    private javax.swing.JTextField verTipo;
    private javax.swing.JTextField verVida;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Usuario> usuarios = new ArrayList<>();
    private Usuario usuarioSelected;
    private ArrayList<Clan> clanes;
    private Clan usuarioSelectedClan;
    private DefaultMutableTreeNode nodoSeleccionado;
}
